# This is a basic workflow to help you get started with Actions

name: Deploy Extension

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: set yarn version
        run: git config --global user.email "github@github.com" &&
             git config --global user.name "Github actions" &&
             git add . && git commit -m 'yarn publish' &&
             yarn version --new-version 1.0.1-${BUILD_NUMBER} --no-git-tag-version

      - uses: lannonbr/vsce-action@master
        with:
          args: "package --yarn"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.vsix
